export enum RequestHistoryEventType {
  REQUEST_CREATED = 'REQUEST_CREATED',
  ASSIGNED = 'ASSIGNED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  INTERNAL_OBSERVATION = 'INTERNAL_OBSERVATION',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  DOCUMENT_VIEWED = 'DOCUMENT_VIEWED',
}
